version: '3'
services:
  apitax:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5085:80
    volumes:
#      - ${PWD}/project.py:/app/project.py
#      - ${PWD}/config.txt:/app/config.txt
      - ./logs:/app/logs
#      - ${PWD}/app:/app/app
